version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinhadb
      - SPRING_DATASOURCE_USERNAME=rinha
      - SPRING_DATASOURCE_PASSWORD=rinha123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha123
      - POSTGRES_DB=rinhadb